## Assignmnet % -- Data Cleanining and Transformation && Model Building

In [35]:
# Data Cleaning 
import pandas as pd
import numpy as np

In [36]:
df1 = pd.read_csv('dataset.csv')
df1.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [37]:
df2 = pd.read_csv('AirQuality.csv')
df2.head()

                                                                                                            Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
10/03/2004;18.00.00;2            6;1360;150;11                 9;1046;166;1056;113;1692;1268;13 6;48 9;0                                                7578;;
10/03/2004;19.00.00;2;1292;112;9 4;955;103;1174;92;1559;972;13 3;47                             7;0  7255;;                                                NaN
10/03/2004;20.00.00;2            2;1402;88;9                   0;939;131;1140;114;1555;1074;11  9;54 0;0                                                7502;;
10/03/2004;21.00.00;2            2;1376;80;9                   2;948;172;1092;122;1584;1203;11  0;60 0;0                                                7867;;
10/03/2004;22.00.00;1            6;1272;51;6                   5;836;131;1205;116;1490;1110;11  2;59 6;0                                                7888;;

In [38]:
df2.columns

Index(['Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;'], dtype='object')

## Data Cleaning

In [39]:
# print the missing values 
print( df1.isnull().sum())
#Remove the missing Values 
df2.fillna( df1.mean() , inplace = True )

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

## 2. Data Integration

In [40]:
## Integrating the two datasets 
# merged_df = pd.merge(df1, df2, on="id")
df2 = df2.loc[:, ~df2.columns.str.contains('^Unnamed')]

In [41]:
df1.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

## 3. Scalinng - 
  - Scaling means bringing all numerical features to the same range/scale.

In [42]:
from sklearn.preprocessing import StandardScaler

In [43]:
scaler = StandardScaler()

In [44]:
df1[['age' , 'chol']] = scaler.fit_transform( df1[['age' ,'chol']])

In [45]:
df1.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0.952197,1,3,145,-0.256334,1,0,150,0,2.3,0,0,1,1
1,-1.915313,1,2,130,0.072199,0,1,187,0,3.5,0,0,2,1
2,-1.474158,0,1,130,-0.816773,0,0,172,0,1.4,2,0,2,1
3,0.180175,1,1,120,-0.198357,0,1,178,0,0.8,2,0,2,1
4,0.290464,0,0,120,2.082050,0,1,163,1,0.6,2,0,2,1

##  4. Encoding --> convert categorial data to 1 and 0

In [46]:
# df1 = pd.get_dummies(df1, columns=['sex'])

## 5. Model Building

In [51]:
from sklearn.model_selection import train_test_split
X = df1.drop('target' , axis = 1)
y = df1['target']
x_train , x_test , y_train , y_test = train_test_split( X , y , test_size = 0.2)

In [53]:
from sklearn.linear_model import LogisticRegression 
model= LogisticRegression()
model =model.fit( x_train , y_train )
y_pred = model.predict( x_test)
print( y_pred)

[1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 0 0 1 0 0 1 1
 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1]

C:\Users\thesa\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [55]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test , y_pred)

0.7704918032786885